name: Generate PDF Resume

on:
  push:
    branches: [ main ]
    paths: [ 'index.html' ]
  workflow_dispatch: # Allow manual triggering

jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Generate PDF
      run: npm run generate-pdf
      
    - name: Commit and push PDF
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add Jhonny_Sanchez_Resume.pdf
        if ! git diff --staged --quiet; then
          git commit -m "🤖 Auto-generate PDF resume"
          git push
        else
          echo "No changes to commit"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}